---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify(classify)
	draft_reply(draft_reply)
	escalate(escalate)
	discard(discard)
	output(output)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify;
	classify -.-> discard;
	classify -.-> draft_reply;
	classify -.-> escalate;
	discard --> output;
	draft_reply --> output;
	escalate --> output;
	output --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
